// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id <project-id> > types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Tables will be generated here
    }
    Views: {
      // Views will be generated here
    }
    Functions: {
      // Functions will be generated here
    }
    Enums: {
      // Enums will be generated here
    }
  }
}
